- hosts: master
  become: yes
  gather_facts: false
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - debug:
        msg: "{{ hostvars['master_one'].join_command }}"

    - name: join cluster
      shell: "{{ hostvars['master_one'].join_command }} >> node_joined.txt"
      become: yes
      register: node_joined
      args:
        chdir: $HOME
        creates: node_joined.txt

    - debug:
        msg: "{{ node_joined }}"
