all:
  children:
    vagrant:
      vars:
        ansible_user: vagrant
      children:
        masters:
          hosts:
            master:
              ansible_ssh_private_key_file: ./.vagrant/machines/master_node/virtualbox/private_key
              ansible_host: 192.168.50.4
        workers:
          hosts:
            worker1:
              ansible_ssh_private_key_file: ./.vagrant/machines/worker_node_1/virtualbox/private_key
              ansible_host: 192.168.50.5
            worker2:
              ansible_ssh_private_key_file: ./.vagrant/machines/worker_node_2/virtualbox/private_key
              ansible_host: 192.168.50.6
